# name is used for the logo image alt text, and in the footer copyright
name: Test ROES Splash
title: Test ROES Splash
description: Test ROES Splash
# baseurl is used if you are using github pages for a project page - this is the project/repo name, always starts with a /
baseurl: /roes-splash-example
permalink: pretty
exclude: ["Gemfile.lock","Gemfile","package.json","rakefile.rb","README.md","s3_website.yml","node_modules","gulpfile.js"]
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

####show message in an alert on home page. Comment it out to hide it.
#message:
#  title: Closed On the 4th of July, Half day on Monday the 3rd
#  content: We will be closing earlier on Monday July 3rd, at 1pm. We will be closed all day on Tuesday July 4th.<br>Back to normal on Wednesday July 5th.
#           <br>Happy 4th of July!

# Google analytics ID - uncomment and add your GA ID
# ga: UA-xxxx-yy

# image for logo, if you don't have one comment it out and use the logo_text below.
# logo_url: /assets/images/pro-lab-prints-logo14.png

# if no logo, comment out above and enter the name and it will show instead
# if the logo_url above is used this will not display
logo_text: ROES Splash

# Main nav is for screens wider than 600px
# Home link is hard coded by default
main_nav:
  - title: "Support"
    url: /support/
 
# on screens smaller than 600px, what nav do you want to show?
# Home is not set by default, the logo works as home link so it could be skipped.
# mobile nav is shown as buttons, there is room for 3-5 depending on how long they are.
mobile_nav:
  - title: Home
    url: /
  
# Expander footer - this has 3 sections, about, links and contact info.
# if you don't need the expanded footer info change this to false.
expanded_footer: true

# expanded footer about section. If you have a large site myou should probably hard code these in the footer include.
# the title is wrapped in an h2 tag
# the content part is wrapped in a p tag. It is ok to have html in it, just be aware of the already included p tag
# important! - you cannot use site.base_url or any other site variables in the content! notice I have hard coded my base_url
ef_about:
  heading: ROES Splash Screen
  content: An easy to use and edit ROES splash screen.
        
# Links section - if they are relative then use url, if they are absolute (different domain) use absolute_url
ef_links:
  heading: Links
  links:
   - title: ROES Intro Video
     external_url: https://prolabprints.com/videos/roes-intro-video/
   - title: ROES Drag and Drop
     external_url: https://prolabprints.com/videos/ROES-drag-and-drop/
   
ef_contact:
  heading: Contact Info
  content: >
          ROES Spash<br />
          123 Main Street <br />
          San Diego, CA 92115 <br />
          Hours: Monday - Friday 9am-6pm<br />
          Phone: (619) 111-2525<br />
          <a href="https://rdyar.github.io/roes-splash-example/" target ="_blank">ROES Splash/</a>
# shows link to strapless on GH
show_footer_credit: false
