- title: Canvas Wraps2
  icon: https://source.unsplash.com/random/500x278?sig=1
  url: roes://canvas-cat/canvaswraps/canvas-info
  description: Ready to hang canvas wall art

- title: Canvas Wraps
  icon: https://source.unsplash.com/random/500x278?sig=1
  url: roes://canvas-cat/canvaswraps/canvas-info
  description: Ready to hang canvas wall art
  
- title: Large Prints and Posters
  icon: https://source.unsplash.com/random/500x278?sig=2
  url: roes://pro-luster-pro-pricing/posters-cat/posters-cat-info
  description: Big prints, 16x20 to 40x60
  
- title: Prints on Metal
  icon: https://source.unsplash.com/random/500x278?sig=3
  url: roes://metal-cat/metal-prints/metal-info
  description: "Stunning! Your image on aluminum"
  
- title: Press Prints on Cardstock
  icon: https://source.unsplash.com/random/500x278?sig=4
  url: roes://press-cat/presscards/press-info
  description: "Flat, folded, trifold..."
  
- title: Fuji Pearl Prints
  icon: https://source.unsplash.com/random/500x278?sig=5
  url: roes://pearl-cat/pearl-subcat/pearl-info
  description: "High gloss metalic photo paper"

- title: Package Printing
  icon: https://source.unsplash.com/random/500x278?sig=6
  url: roes://units-cat/units-subcat/units-info
  description: "Printing for sports, schools, proms etc"    

- title: Die Cut Wallets
  icon: https://source.unsplash.com/random/500x278?sig=7
  url: roes://pro-luster-full-service/pro-luster-fs/dcwfs
  description: Die Cut Wallets with rounded corners

# you can comment out items by putting a # in front of the line. This is handy for seasonal things.
# - title: Double Sided Greeting Cards
#   icon: https://source.unsplash.com/random/500x278?sig=8
#   url: /services/double-sided-greeting-cards/
#   description: "Double sided greeting cards on Card Stock."

# - title: Traditional Photo Greeting Cards
#   icon: https://source.unsplash.com/random/500x278?sig=9
#   url: /services/traditional-photo-greeting-cards/
#   description: "Single sided 4x8 and 5x7 photo greeting cards."

#- title: Photo Calendars
# icon: https://source.unsplash.com/random/500x278?sig=10
# url: /services/custom-photo-calendars/
# description: "Photo Calendars make a great gift idea!"

- title: 8x10 Headshots
  icon: https://source.unsplash.com/random/500x278?sig=11
  url:  roes://pro-luster-pro-pricing/proluster-prints-text/prints-text-info
  description: "8x10 templates with your name"

- title: Prints on Tile
  url: roes://metal-cat/tile-cat/tile-cat-info
  description: "Your photo on a ceramic tile. 4x4, 6x6 and 8x8 sizes available"
  
- title: Engineer Prints
  url: roes://wherever
  description: Big and cheap
  
- title: Banners
  url: roes://wherever
  description: Go big or go home
 
- title: Coffee Migs
  url: roes://wherever
  description: Your mug on a mug! 
  
